<?
	/*ACCESS H*/

	$BACH_CREATE = 0;
	$BACH_CHANGE = 1;
	$BACH_DELETE = 2;
	$BACH_PREVIEW = 3;
	$BACH_PRINT = 4;
	$BACH_JOIN = 5;
	$BACH_JOIN_MODERATOR = 6;

	$BACH_EQUIPMENTGROUP_SUBGROUP = 10;
	$BACH_EQUIPMENTGROUP_SUBGROUP_CREATE = 11;
	$BACH_EQUIPMENTGROUP_SUBGROUP_CHANGE = 12;
	$BACH_EQUIPMENTGROUP_SUBGROUP_DELETE = 13;	
	$BACH_EQUIPMENTGROUP_SUBGROUP_FIELD = 14;	
	$BACH_EQUIPMENTGROUP_SUBGROUP_FIELD_CREATE = 15;
	$BACH_EQUIPMENTGROUP_SUBGROUP_FIELD_CHANGE = 16;
	$BACH_EQUIPMENTGROUP_SUBGROUP_FIELD_DELETE = 17;
	
	
	$BACH_EQUIPMENT_CONSUMABLES = 10;
	$BACH_SERVICEREGLAMENT_EQUIPMENTGROUP = 10;
	
	$BACH_LIST_REQUEST = 10;
	$BACH_LIST_LOCK = 11;
	$BACH_LIST_REQUEST_DELETE = 12;
	$BACH_LIST_REQUEST_PREVIEW = 13;
	$BACH_LIST_UNLOAD = 14;

	$BACH_LIST_CONSUMABLES = 10;
	$BACH_LIST_CONSUMABLES_LOCK = 11;
	$BACH_LIST_CONSUMABLES_DELETE = 12;
	$BACH_LIST_CONSUMABLES_PREVIEW = 13;
	$BACH_LIST_CONSUMABLES_UNLOAD = 14;
	$BACH_LIST_CONSUMABLES_EXECUTE = 15;
	$BACH_LIST_CONSUMABLES_UNDOEXECUTE = 16;
	$BACH_LIST_CONSUMABLES_FEDZAPRAVKA = 17;	
	
	$BACH_CONSUMABLES_TOGARBAGE = 10;
	
	$BACH_MESSAGE_OPTION = 10;

	$BACH_PRERECORD_COMPLETE = 10;

	$BACH_USER_CHANGEPASSWORD = 10;
	$BACH_USER_DIVISION = 11;
	
	$BACH_VISITER_REQUEST = 10;
	$BACH_VISITER_REQUEST_PREVIEW = 11;
	$BACH_VISITER_IMPORT = 12;

	$BACH_AGENCY_DOCUMENT = 10;
	$BACH_AGENCY_DOCUMENT_CREATE = 11;
	$BACH_AGENCY_DOCUMENT_CHANGE = 12;
	$BACH_AGENCY_DOCUMENT_DELETE = 13;	
	
	$BACH_AGENCYGROUP_SUBGROUP = 10;
	$BACH_AGENCYGROUP_SUBGROUP_CREATE = 11;
	$BACH_AGENCYGROUP_SUBGROUP_CHANGE = 12;
	$BACH_AGENCYGROUP_SUBGROUP_DELETE = 13;
	$BACH_AGENCYGROUP_DIVISION = 14;
	$BACH_AGENCYGROUP_DIVISION_CREATE = 15;
	$BACH_AGENCYGROUP_DIVISION_CHANGE = 16;
	$BACH_AGENCYGROUP_DIVISION_DELETE = 17;	
	
	$BACH_DOCUMENT_FIELD = 10;
	$BACH_DOCUMENT_FIELD_CREATE = 11;
	$BACH_DOCUMENT_FIELD_CHANGE = 12;
	$BACH_DOCUMENT_FIELD_DELETE = 13;
	
	$BACH_SERVICE_COPY = 10;
	$BACH_SERVICE_DOCUMENT = 11;
	$BACH_SERVICE_DOCUMENT_CREATE = 12;
	$BACH_SERVICE_DOCUMENT_CHANGE = 13;
	$BACH_SERVICE_DOCUMENT_DELETE = 14;
	$BACH_SERVICE_TEMPLATE = 15;
	$BACH_SERVICE_TEMPLATE_CREATE = 16;
	$BACH_SERVICE_TEMPLATE_CHANGE = 17;
	$BACH_SERVICE_TEMPLATE_DELETE = 18;
	$BACH_SERVICE_LIFESITUATION = 19;
	$BACH_SERVICE_LIFESITUATION_CREATE = 20;
	$BACH_SERVICE_LIFESITUATION_CHANGE = 21;
	$BACH_SERVICE_LIFESITUATION_DELETE = 22;
	$BACH_SERVICE_LIFESITUATION_COPY = 23;

	$BACH_REQUEST_DOCUMENT = 10;
	$BACH_REQUEST_DOCUMENT_CREATE = 11;
	$BACH_REQUEST_DOCUMENT_CHANGE = 12;
	$BACH_REQUEST_DOCUMENT_DELETE = 13;
	$BACH_REQUEST_DOCUMENT_PRINT = 14;

	$BACH_INSTRUCTION_USER = 10;
	$BACH_INSTRUCTION_EXECUTE = 11;
	
	$BACH_REQUEST_ISSUE = 15;
	$BACH_REQUEST_UNDO = 16;
	$BACH_REQUEST_ISSUEERROR = 17;
	$BACH_REQUEST_ISSUEERROR = 17;
	$BACH_REQUEST_UNDOERROR = 18;

	$BACH_REQUEST_INFOPHONE = 19;
	$BACH_REQUEST_INFOMAIL = 20;
	$BACH_REQUEST_MOVEINFOLIST = 21;

	$BACH_REQUEST_TAKE = 22;
	$BACH_REQUEST_VERIFY = 23;
	$BACH_REQUEST_ERROR = 24;
	$BACH_REQUEST_RETURN = 25;
	$BACH_REQUEST_UNDOWAIT = 26;
	$BACH_REQUEST_UNDOREADY = 27;
	$BACH_REQUEST_UNDORECD = 28;
	$BACH_REQUEST_UNDOISSUE = 29;
	$BACH_REQUEST_UNDOLOST = 30;
	$BACH_REQUEST_UNDOISSUEERROR = 31;
	$BACH_REQUEST_LOST = 32;
	$BACH_REQUEST_LOSTERROR = 33;
	$BACH_REQUEST_INFOSMS = 34;
	
	$BACH_USERGROUP_COPY = 10;
	$BACH_USERGROUP_ORDER = 11;
	
	$BACH_INTERSERVICE_FUNCTION = 10;
	$BACH_INTERSERVICE_FUNCTION_CREATE = 11;
	$BACH_INTERSERVICE_FUNCTION_CHANGE = 12;
	$BACH_INTERSERVICE_FUNCTION_DELETE = 13;	

	$BACH_EQUIPMENTOFDIVISION_REPAIR = 10;
	$BACH_EQUIPMENTOFDIVISION_REPAIR_PREVIEW = 11;
	
	$BACH_REQUEST_EXECUTE = 10;
	$BACH_REQUEST_UNDOEXECUTE = 11;	
	$BACH_REQUEST_REPAIR = 12;
	$BACH_REQUEST_REPAIR_CREATE = 13;
	$BACH_REQUEST_REPAIR_CHANGE = 14;
	$BACH_REQUEST_REPAIR_DELETE = 15;
	$BACH_REQUEST_REPAIR_PREVIEW = 16;
	$BACH_REQUEST_REPAIR_PRINT = 17;
	$BACH_REQUEST_USER = 18;
	
	$BACH_REQUEST_CONSUMABLES = 19;
	$BACH_REQUEST_CONSUMABLES_CREATE = 20;
	$BACH_REQUEST_CONSUMABLES_CHANGE = 21;
	$BACH_REQUEST_CONSUMABLES_DELETE = 22;
	
	$BACH_REQUEST_HOTLINE_REGISTER = 23;
	$BACH_REQUEST_HOTLINE_CLOSE = 24;
	
	$BACH_REQUEST_DOCUMENT = 25;
	$BACH_REQUEST_DOCUMENT_CREATE = 26;
	$BACH_REQUEST_DOCUMENT_CHANGE = 27;
	$BACH_REQUEST_DOCUMENT_DELETE = 28;
	$BACH_REQUEST_DOCUMENT_PREVIEW = 29;
	$BACH_REQUEST_DOCUMENT_EXECUTE = 30;
	$BACH_REQUEST_DOCUMENT_UNDOEXECUTE = 31;
	$BACH_REQUEST_DOCUMENT_PRINT = 32;
	$BACH_REQUEST_DOCUMENT_SIGNATURE = 33;
	$BACH_REQUEST_DOCUMENT_SIGNATURE_CREATE = 34;
	$BACH_REQUEST_DOCUMENT_SIGNATURE_CHANGE = 35;
	$BACH_REQUEST_DOCUMENT_SIGNATURE_DELETE = 36;
	$BACH_REQUEST_DOCUMENT_FILE = 37;
	
	$BACH_REPAIR_JUMP = 10;	
	
	$BACH_DOCUMENT_BRANCH_EXECUTE = 10;
	$BACH_DOCUMENT_BRANCH_UNDOEXECUTE = 11;
	$BACH_DOCUMENT_BRANCH_FILE = 12;
	
	$BACH_DIVISION_REQUEST = 10;
	$BACH_DIVISION_REQUEST_PREVIEW = 11;	
	
	$BACH_NEWSGROUP_SUBGROUP = 10;
	$BACH_NEWSGROUP_SUBGROUP_CREATE = 11;
	$BACH_NEWSGROUP_SUBGROUP_CHANGE = 12;
	$BACH_NEWSGROUP_SUBGROUP_DELETE = 13;	
	
	$BACH_CONSUMABLESFROMDIVISION_DO = 10;
	$BACH_CONSUMABLESFROMDIVISION_BACK = 11;
	
	/*ACCESS L*/

	
	$BACL_DOCUMENT_BRANCH_CHANGE_BRANCH = 0;
	$BACL_DOCUMENT_BRANCH_SHOWALL = 1;
	
	$BACL_PERSON_CHANGE_BRANCH = 0;
	$BACL_PERSON_SHOWALL = 1;
	
	$BACL_INSTRUCTION_CHANGE_BRANCH = 0;
	$BACL_INSTRUCTION_SHOWALL = 1;
	
	$BACL_SOFTWAREUPDATE_SHOWALL = 0;
	$BACL_SOFTWAREUPDATE_CHANGE_BRANCH = 1;
	
	$BACL_SERVICEEQUIPMENT_SHOWALL = 0;
	$BACL_SERVICEEQUIPMENT_CHANGE_BRANCH = 1;	
	
	$BACL_MFC_CHANGE_PCDC = 0;

	$BACL_CONSULTATION_PRINT = 0;

	$BACL_MESSAGE_SENDALL = 0;
	$BACL_MESSAGE_CHANGE_BRANCH = 1;

	$BACL_REPORT_SERVICEANDCONSULTATION = 0;
	$BACL_REPORT_USER = 3;
	$BACL_REPORT_EXTRACT = 4;
	$BACL_REPORT_CHANGE_OFFICE = 5;

	$BACL_EXPORT_SETTINGANDREQUEST = 0;
	$BACL_EXPORT_SERVICE = 1;

	$BACL_IMPORT_DIRECTORY = 3;

	$BACL_VISITER_PREVIEWEX = 0;
	$BACL_VISITER_DELETE_ISREQUEST = 1;
	$BACL_VISITER_CHANGE_ISREQUEST = 2;
	$BACL_VISITER_CHANGE_WARNING_ISREQUEST = 3;
	$BACL_VISITER_CREATE_BLOCKTOSEARCH = 4;
	$BACL_VISITER_CREATE_PHOTO = 5;
	$BACL_VISITER_CHANGE_PHOTO = 6;

	$BACL_EQUIPMENTOFDIVISION_CHANGE_ISREPAIR = 1;
	$BACL_EQUIPMENTOFDIVISION_CHANGE_WARNING_ISREPAIR = 2;
	$BACL_EQUIPMENTOFDIVISION_DELETE_ISREPAIR = 3;	
	$BACL_EQUIPMENTOFDIVISION_SHOWALL = 4;
	$BACL_EQUIPMENTOFDIVISION_CHANGE_BRANCH = 5;	
	
	$BACL_CONSUMABLESOFDIVISION_SHOWALL = 1;
	$BACL_CONSUMABLESOFDIVISION_CHANGE_BRANCH = 2;
	
	
	
	$BACL_REQUEST_PREVIEWEX = 0;
	$BACL_REQUEST_CHANGE_USEROWNER = 1;
	$BACL_REQUEST_ACCESS_RESETFORRETURN = 2;
	$BACL_REQUEST_SEND_MESSAGERETURN = 3;
	$BACL_REQUEST_SEND_MESSAGETAKE = 4;
	$BACL_REQUEST_SHOW_EREXPIREDREQUESTINFO = 5;
	$BACL_REQUEST_PRINT_LETTEREREXPIRED = 6;
	$BACL_REQUEST_CHANGE_INFOSTATE = 7;
	$BACL_REQUEST_SHOWALL = 8;
	$BACL_REQUEST_CHANGE_BRANCH = 9;
	$BACL_REQUEST_CHANGE_ALLSTATE = 10;
	$BACL_REQUEST_SIMPLE_INTERFACE = 11;

	$BACL_REPAIR_CHANGE_BRANCH = 1;
	$BACL_REPAIR_SHOWALL = 2;
	
	$BACL_DOCUMENT_BRANCH_CHANGE_BRANCH = 1;
	$BACL_DOCUMENT_BRANCH_SHOWALL = 2;
	
	$BACL_USER_ISNULLPASSWORD = 0;
	$BACL_USER_CHANGE_LOGIN = 1;
	$BACL_USER_CHANGE_USERGROUP = 2;
	$BACL_USER_CHANGE_STATUS = 3;
	$BACL_USER_PASSWORD_REQUIREOLD = 5;
	$BACL_USER_CHANGE_BRANCH = 6;

	$BACL_STATISTIC_SHOW_IN_TOTAL = 0;
	$BACL_STATISTIC_SHOW_IN = 1;
	$BACL_STATISTIC_SHOW_OUT_TOTAL = 2;
	$BACL_STATISTIC_SHOW_OUT = 3;
	$BACL_STATISTIC_SHOW_INFOCENTER_TOTAL = 4;
	$BACL_STATISTIC_SHOW_INFOCENTER = 5;
	$BACL_STATISTIC_SHOW_RATING_A_TOTAL = 6;
	$BACL_STATISTIC_SHOW_RATING_A = 7;
	$BACL_STATISTIC_CHANGE_OFFICE = 8;

	$BACL_NEWS_CHANGEEX = 0;
	$BACL_NEWS_DELETEEX = 1;
	$BACL_NEWS_CHANGE_BRANCH = 2;
	
	$BACL_BRANCH_CHANGE_STATUS = 0;
	$BACL_BRANCH_CHANGE_DEFAULT = 1;
	
	$BACL_DIVISION_CHANGE_STATUS = 0;
	$BACL_DIVISION_CHANGE_BRANCH = 1;
	
	$BACL_AGENCY_CHANGE_STATUS = 0;
	
	$BACL_SERVICE_CHANGE_STATUS = 0;
	
	$BACL_LIST_CONSUMABLES_CHANGE_BRANCH = 0;
	$BACL_LIST_CHANGE_OFFICE = 0;
	$BACL_LIST_CHANGE_BRANCH = 0;
	
	$BACL_PRERECORD_CHANGE_OFFICE = 0;
	
	$BACL_METRIC_CHANGE_OFFICE = 0;
	
	$BACL_EQUIPMENT_CREATE_EQUIPMENTNAME = 0;
	$BACL_EQUIPMENT_CREATE_EQUIPMENTMANUFACTURER = 1;
	
	$BACL_CONSUMABLES_CREATE_CONSUMABLESNAME = 0;
	
	$BACL_REPORT_CHANGE_BRANCH = 0;
	$BACL_REPORT_SERVICE = 1;
	$BACL_REPORT_PERSONNEL = 2;
	$BACL_REPORT_TRAVEL = 3;
	$BACL_REPORT_CONSUMABLES = 4;
	
	$BACL_TIMESHEET_CHANGE_BRANCH = 0;
	$BACL_TIMESHEET_CHANGE = 1;
	
	$BACL_TRAVEL_SHOWALL = 0;
	$BACL_TRAVEL_CHANGE_BRANCH = 1;
	$BACL_TRAVEL_PRINT_CHANGE_USER = 2;
	$BACL_TRAVEL_CHANGE_USER = 3;
	$BACL_TRAVEL_PAY_DOCUMENT = 4;
	$BACL_TRAVEL_PAY_DOCUMENT_CREATE = 5;
	$BACL_TRAVEL_PAY_DOCUMENT_CHANGE = 6;
	$BACL_TRAVEL_PAY_DOCUMENT_DELETE = 7;
	
	$BACL_DOCUMENT_STATUS = 14;
	$BACL_DOCUMENT_STATUS_CREATE = 15;
	$BACL_DOCUMENT_STATUS_CHANGE = 16;
	$BACL_DOCUMENT_STATUS_DELETE = 17;
	
	$BACL_DOCUMENT_SIGNATURE = 18;
	$BACL_DOCUMENT_SIGNATURE_CREATE = 19;
	$BACL_DOCUMENT_SIGNATURE_CHANGE = 20;
	$BACL_DOCUMENT_SIGNATURE_DELETE = 21;
	
	$BACL_SIGNATURE = 10;
	$BACL_SIGNATURE_CREATE = 11;
	$BACL_SIGNATURE_CHANGE = 12;
	$BACL_SIGNATURE_DELETE = 13;
	
	
	$BACL_FUELCHECK_SHOWALL = 0;
	$BACL_FUELCHECK_CHANGE_BRANCH = 1;
	
	$BACL_FILESHARE_CHANGE_BRANCH = 0;
	
	$BACL_SERVICECENTER_CHANGE_BRANCH = 0;
	$BACL_STAFF_LIST_CHANGE_BRANCH = 0;
	
	
	
	$BACL_RECORD_PUBLISH =0;
	
	/*ACCESS E*/
	$BACE_REQUEST_DELETE = 0;
	$BACE_REQUEST_CHANGE_SERVICE = 1;
	$BACE_REQUEST_CHANGE_LIFESITUATION = 2;
	$BACE_REQUEST_CHANGE_DATEISSUEPLANED = 3;
	$BACE_REQUEST_CHANGE_AGENCY = 4;
	$BACE_REQUEST_CHANGE_VISITER = 5;
	$BACE_REQUEST_DOCUMENT = 6;
	$BACE_REQUEST_CHANGE_PROXY = 7;

	$BACE_REQUEST_CHANGE_ACCESS_DELETE = 38;
	$BACE_REQUEST_CHANGE_ACCESS_CHANGE_SERVICE = 37;
	$BACE_REQUEST_CHANGE_ACCESS_CHANGE_LIFESITUATION = 36;
	$BACE_REQUEST_CHANGE_ACCESS_CHANGE_DATEISSUEPLANED = 35;
	$BACE_REQUEST_CHANGE_ACCESS_CHANGE_AGENCY = 34;
	$BACE_REQUEST_CHANGE_ACCESS_CHANGE_VISITER = 33;
	$BACE_REQUEST_CHANGE_ACCESS_DOCUMENT = 32;
	$BACE_REQUEST_CHANGE_ACCESS_CHANGE_PROXY = 31;

	/*LIBERY*/

	$BACL_ISADMIN = 0;
?>