<?
	$DB_NAME = 'IAC';
	$DB_HOST = 'localhost';
	$DB_USER_NAME = 'iac';
	$DB_USER_PASSWORD = 'iac';

	$DB_VERSION_MAJOR = 1;
	$DB_VERSION_MINOR = 0;
	$DB_VERSION_RELEASE = 0;
	$DB_VERSION_BUILD = 1;
	$DB_VERSION_SEPARATOR = '.';

	$DB_VERSION_FULL = $DB_VERSION_MAJOR.$DB_VERSION_SEPARATOR.$DB_VERSION_MINOR.$DB_VERSION_SEPARATOR.$DB_VERSION_RELEASE.$DB_VERSION_SEPARATOR.$DB_VERSION_BUILD;
	$DB_VERSION_SHORT = $DB_VERSION_MAJOR.$DB_VERSION_SEPARATOR.$DB_VERSION_MINOR;
	$DB_VERSION = $DB_VERSION_FULL;
?>