<?
	$LOGO_TITLE = 'АИС "Аналитика"';
	$LOGO_COPYRIGHT = 'Copyright (С) 2019';

	$LOGO_PRODUCT_NAME = 'АИС "Аналитика"';
	$LOGO_PRODUCT_NAME_FULL = 'Автоматизированная информационная система "Аналитика"';

	$LOGO_PRODUCT_VERSION_MAJOR = 1;
	$LOGO_PRODUCT_VERSION_MINOR = 0;
	$LOGO_PRODUCT_VERSION_RELEASE = 0;
	$LOGO_PRODUCT_VERSION_BUILD = 1;

	$LOGO_PRODUCT_VERSION_SEPARATOR = '.';

	$LOGO_PRODUCT_VERSION_FULL = $LOGO_PRODUCT_VERSION_MAJOR.$LOGO_PRODUCT_VERSION_SEPARATOR.$LOGO_PRODUCT_VERSION_MINOR.$LOGO_PRODUCT_VERSION_SEPARATOR.$LOGO_PRODUCT_VERSION_RELEASE.$LOGO_PRODUCT_VERSION_SEPARATOR.$LOGO_PRODUCT_VERSION_BUILD;
	$LOGO_PRODUCT_VERSION_SHORT = $LOGO_PRODUCT_VERSION_MAJOR.$LOGO_PRODUCT_VERSION_SEPARATOR.$LOGO_PRODUCT_VERSION_MINOR;
	$LOGO_PRODUCT_VERSION = $LOGO_PRODUCT_VERSION_FULL;
	
	$LOGO_LIC_KEYWORD = 'IAC';
?>